### ISSUE TITLE
maybe IndirectArrays?

### ISSUE THREAD

**Issue by johnnychen94** [cscherrer/PermutedArrays.jl#1]
Looks like the functionality here can be covered by https://github.com/JuliaArrays/IndirectArrays.jl?

Although I don't quite get the usage of `iperm` here; I didn't benchmark it, the doubled memory allocation might not worth the reduced computation in `swap!`.

**Comment by cscherrer** [comment]
Thanks @johnnychen94 , I started out with that, but the `setindex!` there is
```
@inline function Base.setindex!(A::IndirectArray, x, i::Int)
    @boundscheck checkbounds(A.index, i)
    idx = findfirst(isequal(x), A.values)
    if idx == nothing
        push!(A.values, x)
        A.index[i] = length(A.values)
    else
        A.index[i] = idx
    end
    return A
end
```
which doesn't quite work for this case.

I'm not sure yet about `iperm`. It might well be unnecessary, but at least for early stages it makes it easy to check that everything is consistent. I might drop it as we add more functionality if it becomes clear we don't need it.
